#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="windows-x86_64"
DEPS_ROOT="${PROJECT_DIR}/worker/native_deps/${TARGET}"
CACHE_DIR="${PROJECT_DIR}/build/downloads/${TARGET}"
BUILD_DIR="${PROJECT_DIR}/build/deps/${TARGET}"
ONNXRUNTIME_VERSION="${ONNXRUNTIME_VERSION:-1.27.0}"
LIBJPEG_TURBO_VERSION="${LIBJPEG_TURBO_VERSION:-3.2.0}"
CLEAN=0

usage() {
  cat <<'EOF'
Usage: tools/fetch-worker-windows-deps.sh [options]

Options:
  --clean        Remove downloaded/extracted dependency directories before fetching/building
  -h, --help     Show this help

Environment:
  ONNXRUNTIME_VERSION       Default: 1.27.0
  LIBJPEG_TURBO_VERSION     Default: 3.2.0
  CC                        Optional. Defaults to x86_64-w64-mingw32-gcc.
  CXX                       Optional. Defaults to x86_64-w64-mingw32-g++.
  WINDRES                   Optional. Defaults to x86_64-w64-mingw32-windres.

Output:
  worker/native_deps/windows-x86_64/onnxruntime
  worker/native_deps/windows-x86_64/jpeg
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --clean)
      CLEAN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1" >&2
    exit 1
  fi
}

require_command curl
require_command unzip
require_command tar
require_command cmake
require_command "${CC:-x86_64-w64-mingw32-gcc}"
require_command "${CXX:-x86_64-w64-mingw32-g++}"

mkdir -p "${CACHE_DIR}" "${BUILD_DIR}" "${DEPS_ROOT}"

if [ "${CLEAN}" = "1" ]; then
  rm -rf \
    "${DEPS_ROOT}/onnxruntime" \
    "${DEPS_ROOT}/jpeg" \
    "${BUILD_DIR}/libjpeg-turbo-${LIBJPEG_TURBO_VERSION}" \
    "${BUILD_DIR}/libjpeg-turbo-build"
fi

download_if_missing() {
  local url="$1"
  local target="$2"
  if [ ! -f "${target}" ]; then
    echo "Downloading ${url}"
    curl -L --fail --retry 3 --output "${target}" "${url}"
  else
    echo "Using cached download: ${target}"
  fi
}

ONNXRUNTIME_ZIP="${CACHE_DIR}/onnxruntime-win-x64-${ONNXRUNTIME_VERSION}.zip"
ONNXRUNTIME_URL="https://github.com/microsoft/onnxruntime/releases/download/v${ONNXRUNTIME_VERSION}/onnxruntime-win-x64-${ONNXRUNTIME_VERSION}.zip"
download_if_missing "${ONNXRUNTIME_URL}" "${ONNXRUNTIME_ZIP}"
rm -rf "${DEPS_ROOT}/onnxruntime"
mkdir -p "${DEPS_ROOT}/onnxruntime"
unzip -q "${ONNXRUNTIME_ZIP}" -d "${BUILD_DIR}"
ONNXRUNTIME_EXTRACTED="${BUILD_DIR}/onnxruntime-win-x64-${ONNXRUNTIME_VERSION}"
if [ ! -d "${ONNXRUNTIME_EXTRACTED}" ]; then
  echo "ERROR: expected extracted ONNXRuntime directory not found: ${ONNXRUNTIME_EXTRACTED}" >&2
  exit 1
fi
cp -a "${ONNXRUNTIME_EXTRACTED}/." "${DEPS_ROOT}/onnxruntime/"

LIBJPEG_TURBO_TARBALL="${CACHE_DIR}/libjpeg-turbo-${LIBJPEG_TURBO_VERSION}.tar.gz"
LIBJPEG_TURBO_URL="https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${LIBJPEG_TURBO_VERSION}/libjpeg-turbo-${LIBJPEG_TURBO_VERSION}.tar.gz"
download_if_missing "${LIBJPEG_TURBO_URL}" "${LIBJPEG_TURBO_TARBALL}"
rm -rf "${BUILD_DIR}/libjpeg-turbo-${LIBJPEG_TURBO_VERSION}" "${BUILD_DIR}/libjpeg-turbo-build" "${DEPS_ROOT}/jpeg"
tar -xzf "${LIBJPEG_TURBO_TARBALL}" -C "${BUILD_DIR}"

CMAKE_ARGS=(
  -S "${BUILD_DIR}/libjpeg-turbo-${LIBJPEG_TURBO_VERSION}"
  -B "${BUILD_DIR}/libjpeg-turbo-build"
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX="${DEPS_ROOT}/jpeg"
  -DCMAKE_SYSTEM_NAME=Windows
  -DCMAKE_SYSTEM_PROCESSOR=x86_64
  -DCMAKE_C_COMPILER="${CC:-x86_64-w64-mingw32-gcc}"
  -DCMAKE_CXX_COMPILER="${CXX:-x86_64-w64-mingw32-g++}"
  -DCMAKE_RC_COMPILER="${WINDRES:-x86_64-w64-mingw32-windres}"
  -DENABLE_SHARED=1
  -DENABLE_STATIC=1
  -DWITH_JAVA=0
  -DWITH_TESTS=0
  -DWITH_SIMD=0
)
if command -v ninja >/dev/null 2>&1; then
  CMAKE_ARGS+=(-G Ninja)
fi

cmake "${CMAKE_ARGS[@]}"
cmake --build "${BUILD_DIR}/libjpeg-turbo-build"
cmake --install "${BUILD_DIR}/libjpeg-turbo-build"

if [ ! -f "${DEPS_ROOT}/onnxruntime/include/onnxruntime_c_api.h" ]; then
  echo "ERROR: ONNXRuntime dependency is incomplete: missing include/onnxruntime_c_api.h" >&2
  exit 1
fi
if [ ! -f "${DEPS_ROOT}/jpeg/include/jpeglib.h" ]; then
  echo "ERROR: JPEG dependency is incomplete: missing include/jpeglib.h" >&2
  exit 1
fi

cat > "${DEPS_ROOT}/README.txt" <<EOF
AV_ImgData Windows native worker dependencies.

Generated by:
  tools/fetch-worker-windows-deps.sh

Versions:
  ONNXRuntime ${ONNXRUNTIME_VERSION}
  libjpeg-turbo ${LIBJPEG_TURBO_VERSION}

These files are local build dependencies and should not be committed.
EOF

echo "Windows worker native dependencies ready: ${DEPS_ROOT}"
echo "ONNXRuntime: ${DEPS_ROOT}/onnxruntime"
echo "JPEG:        ${DEPS_ROOT}/jpeg"
